# Generated by Django 4.1.7 on 2023-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Answer',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='Security_question',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
