# Generated by Django 4.1.7 on 2023-03-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_accounts_answer_accounts_security_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='Answer',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Security_question',
            field=models.CharField(max_length=50),
        ),
    ]
