# Generated by Django 4.1.7 on 2023-03-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_accounts_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='Security_question',
        ),
    ]
