# Generated by Django 4.1.7 on 2023-03-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_accounts_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Security_Question',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
