# Generated by Django 4.1.7 on 2023-03-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_accounts_anser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='Anser',
            new_name='Answer',
        ),
    ]
