# Generated by Django 4.1.7 on 2023-04-30 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_accounts_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Poster', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='Images')),
                ('Title', models.CharField(max_length=20)),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
    ]
