# Generated by Django 4.1.7 on 2023-05-12 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image_id', models.IntegerField()),
                ('Poster', models.CharField(max_length=20)),
                ('Details', models.CharField(max_length=1000)),
                ('Likes', models.IntegerField()),
                ('User', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100000), size=None)),
            ],
        ),
    ]
